my_site/blog/urls.py
from django.urls import path
from blog.views import post_detail, post_list,post_search
app_name= 'blog'
from .feeds import LatestPostFeed
urlpatterns = [
        path('', post_list, name="post_list"),
        path('tag/<slug:tag_slug>', post_list, name="post_list_by_tag"),

        path('<int:year>/<int:month>/<int:day>/<slug:post>',
                post_detail,
                name='post_detail'),
        path('feed/', LatestPostFeed(), name="post_feed"),
        path('search/', post_search, name= "post_search")
        ]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog_app'))
]

my_site/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super( PublishedManager, self)\
                        .get_queryset()\
                        .filter(status='published'
                            )



class Post(models.Model):
    STATUS_CHOICES=(
            ('draft','Draft'),
            ('published','Published')
        )
    title = models.CharField(max_length=250)
    #short label to be used for URLs
    slug  = models.SlugField(max_length=250,
        unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="blog_posts")#many_to_one relationship with user model of django
    body = models.TextField()
    #time when post published
    publish = models.DateTimeField(default = timezone.now)
    #time when post was created
    created = models.DateTimeField(auto_now_add=True)
    #time when post was updated
    updated = models.DateTimeField(auto_now=True)
    status  = models.CharField(max_length=10,
                               choices=STATUS_CHOICES,
                               default='draft')
    objects = models.Manager()

    published = PublishedManager()

    tags = TaggableManager()
    class Meta:
        #post ordering in descending using publish field
        ordering = ('-publish',)

    def __str__(self):
        #default human-readable representation of the object
        return self.title


    def get_absolute_url(self):
        return reverse('blog:post_detail',
            args=[self.publish.year,
                    self.publish.month,
                    self.publish.day,
                    self.slug
                    ])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering:('created',)
    def __str__(self):
        return 'comment by {} on {} '.format(self.name, self.post)

my_site/blog/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.db import models
from django import forms
from .models import Comment
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in (self.fields['username'],self.fileds['password'],self.fields['email']):
            field.widget.attrs.update({'class':'form-control'})
    class Meta:
        model = User
        fields = ['username', 'password', 'email']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in (self.fields['name'],self.fields['email'],self.fields['body']):
                field.widget.attrs.update({'class':'form-control'})



class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

my_site/blog/views.py
from .models import Post, Comment
from django.shortcuts import render
from taggit.models import Tag
from .forms import UserForm, CommentForm, SearchForm
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery,SearchRank

def register(request):
    registered=False
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        if user_form.is_valid() :
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered=True
            print("registered")
        else:print(user_form.errors)
    else:
        user_form=UserForm()
    return render(request, "blog/register.html",{'user_form':user_form,'registered':registered})

def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3) #3 posts per page
    page = request.GET.get('page')
    tags = Tag.objects.all()
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                    'blog/post_list.html',
                    {'page':page,
                    'posts':posts,'tag':tag, 'tags':tags})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                            status = 'published',
                            publish__year=year,
                            publish__month=month,
                            publish__day=day
                            )
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method=="POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
    .order_by('-same_tags','-publish')[:4]

    return render(request,'blog/post_detail.html', {'comments':comments,
            'post':post,
            'new_comment':new_comment,
            'comment_form':comment_form,
            'similar_posts':similar_posts
        })


def post_search(request):
    form = SearchForm()
    query = None
    results =[]
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)).filter(search=search_query).order_by('-rank')

    return render(request, 'blog/post_search.html',{'form':form, 'query':query,'results':results})

my_site/templates/blog/base.html
<!Doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Roboto|Roboto+Condensed&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{%block title%}Akash's Blog{%endblock%}</title>
  </head>
  <body>

    <div class="container-fluid ">
        <div class="row">
        <div class="col-lg-2 bg-info p-3 text-center px-1 text-white">  <h1 class="display-4">Akash's Blog</h1></div>
        <div class="col-lg-10">
        <nav class="nav bg-dark p-3 justify-content-end px-5">
            <a href="{% url 'blog:post_list' %}" class="nav-link btn-link text-white">Home</a>
            <a href="{% url 'blog:post_search' %}" class="nav-link btn-link text-white">Search post</a>

            <a href="{% url 'blog:post_feed'%}" class="nav-link btn btn-link bg-danger  text-white" >Subscribe to my RSS feed</a>
        </nav>
        </div>
        </div>

            <!-- <h1>Posts</h1> -->
        {% block content %}

        {% endblock %}
        <footer class="footer nav bg-success p-3 justify-content-center px-5" style="position: relative; bottom: 0px; width:100%;margin-right: 50px;">
            <a href="{% url 'blog:post_list' %}" class="nav-link btn-link text-white">blog</a>
            <a href="https://twitter.com/Akashverm4" class="nav-link btn-link text-white">Twitter</a>
            <a href="https://www.linkedin.com/in/akash-verma-8473a6151/" class="nav-link btn-link text-white">LinkedIn</a>
        </footer>
        </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

my_site/templates/blog/pagination.html
<div class="pagination justify-content-center">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{page.number}} of {{page.paginator.num_pages}}
        </span>
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">Next</a>
        {% endif %}
    </span>
</div>

my_site/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load markdown_extras %}

{% block content %}
<div class="row">
        <div class="col-lg-8 mt-5 offset-lg-1 bg-white text-dark">
            <h2 class="p-1 text-info"style="font-family: Montserrat, Roboto Condensed; font-size: 30px" >{{post.title}}

            </h2>

            <div class="container  p-2">

            <div class="justify-content-center text-success"><h5>  {{post.created.date}}|Tags:
                {% for tag in post.tags.all %}
                   <a style="border-radius:10px; padding:3px;font-size: 15px;font-family: monospace;" class="text-decoration-none text-white bg-dark" href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a>
                {% if not forloop.last %}{% endif %}
                {% endfor %}</h5></div>
            <hr>
            <p class="text-justify col-lg-6 p-3 px-3 m-3" style="font-family: monospace;">{{post.body| markdown| safe |linebreaks}}</p>
            </div>

            {% with comments.count as total_comments %}
                <h2>{{total_comments}} comment{{total_comments|pluralize}}</h2>
            {% endwith %}
            {% for comment  in comments %}
                <p class="info">
                    Comment {{forloop.counter}}by {{comment.name}}
                    <br><sub><strong style="font-family: sans-serif;"class="text-success">{{comment.created.date}}</strong></sub>
                    <div class="bg-light bg-info" style="border:1px solid black; padding: 5px"><i style="background-color: teal;color: white;padding: 2px">{{comment.body}}</i>
                    </div>

                </p>


            {%empty%}

            <p>There are no comments yet</p>
            {% endfor %}

            {%if new_comment %}
            <h2>Your comment has been added.</h2>

            {%else%}


            <h2>Add a new comment here...</h2>
            <form action="" method="post " class="">
                {{comment_form.as_p}}
                {%csrf_token%}
                <p><input type="submit" class=" btn btn-success" value="Add comment"></p>
            </form>
        </div>
        <div class="jumbotron col-lg-2">
            <h2 class="heading">Similar posts</h2>
            {% for post in similar_posts %}
                    <a href="{{post.get_absolute_url }}"style="border-radius:5px; padding:3px;font-size: 15px;font-family: Roboto;background-color: teal;" class=" text-decoration-none text-white ">{{post.title}} <br>
                    </a>

            {% empty %}
                There are no similar posts yet
            {% endfor %}
        </div>
    </div>
    {% endif %}
{% endblock %}

my_site/templates/blog/post_list.html
{% extends 'blog/base.html' %}


        {% block content %}

        <div class="row">

          <div class="col-lg-8 offset-lg-1 bg-white text-dark pt-3">
  <h1 class="px-5">Top Posts</h1>

            <div class="container mt-4 p-4">
              {% if tag %}
              <h2>Posts tagged with "{{tag.name}}"</h2>
              {% endif %}
            {% for post in posts%}

               <a href="{{post.get_absolute_url}}" class="btn-link text-decoration-none text-info " style="font-family: Montserrat, Roboto Condensed; font-size: 20px">{{post.title}}</a>

               <strong class="text-success"><sub>{{post.publish}} by </sub><sub class="text-danger"></sub></strong>
               <p  class="text-justify">{{ post.body|truncatewords:30|linebreaks }}</p>

               <hr>
                <p>Tags:
                {% for tag in post.tags.all %}
                   <a style="border-radius:10px; padding:3px;font-size: 15px;font-family: monospace;" class="text-decoration-none text-white bg-dark" href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a>
                {% if not forloop.last %}{% endif %}
                {% endfor %}
              </p>
              <div class="p-2 m-2"></div>
            {% endfor %}
                    {% include 'blog/pagination.html' with page=posts %}
            </div>

            </div>
            <div class="container col-lg-2 bg-light">
              <p><h2 class="bg-white text-center">Tags:</h2>
                <ul class="text-decoration-none p-2">
                {% for tag in tags %}
                  <span style="text-decoration-style: none;" class="text-white"> <a style="border-radius:10px; padding:3px;font-size: 15px;font-family: monospace;" class="text-decoration-none text-white bg-dark text-justify" href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a>
                {% if not forloop.last %}{% endif %}
                  </span>
                {% endfor %}

                </ul>
              </p>

              </div>

            </div>
        {% endblock %}

my_site/templates/blog/post_search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
{% if query %}
<h1>Posts containing "{{ query }}"</h1>
<h3>
{% with results.count as total_results %}
Found {{ total_results }} result{{ total_results|pluralize }}
{% endwith %}
</h3>
{% for post in results %}
<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
{{ post.body|truncatewords:5 }}
{% empty %}
<p>There are no results for your query.</p>
{% endfor %}
<p><a href="{% url 'blog:post_search' %}">Search again</a></p>
{% else %}
<h1>Search for posts</h1>
<form action="." method="get">
{{ form.as_p }}
<input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}

my_site/templates/blog/register.html
{% block content %}

    {% if registered %}
        <strong>Thank You for Registering With Us </strong>
        {% else %}
        <strong class="display-3 mb-2">Register Here...</strong>

        <form action="{%url 'register' %}" method="POST">
            {% csrf_token %}
            {{user_form.as_p}}
            <input type="submit" class="btn btn-success" name="submit" value="Register">
            <p class="p-2 m-1">Already a member? <a href="{%url 'login' %}">LOGIN here ...</a></p>
        </form>
    {% endif  %}

{% endblock %}